### ISSUE TITLE
Misspelled: (lastest) instead of latest  of Latest Jenkins Build No. field

### ISSUE THREAD

**Issue by tagoylo** [sdgtt/constellation#16]
(lastest) instead of latest

![image](https://github.com/user-attachments/assets/f7cde83a-cad4-424f-aee8-5d9cb2e89ecf)

**Comment by cseptimo** [comment]
resolved 
![image](https://github.com/user-attachments/assets/24f97b9e-7d59-4b07-82b1-f12f2c99a94e)
