### ISSUE TITLE
board name not fixed while scrolling the end of table

### ISSUE THREAD

**Issue by tagoylo** [sdgtt/constellation#27]
At first it is fixed but when almost at the bottom of the table it also scrolls up. Is this expected? See video.

https://github.com/user-attachments/assets/de3caf18-0de8-4a6d-a524-4f6e1eece189

**Comment by cseptimo** [comment]
it is expected since there are 2 scrolls in the page. I'll try to disable the main scroll and retain the table's scroll bar.
